### ISSUE TITLE
AbstractUnArchiver.extractFile fails on Windows when extracting a symbolic link

### ISSUE THREAD

**Issue by axelfontaine** [codehaus-plexus/plexus-archiver#66] opened 2017-07-04 13:38 UTC
Except if the console was started with admin privileges. Issuing a warning would most likely be a much user-friendlier solution.

Stack trace:
```
java.nio.file.FileSystemException: C:\mydir\server-jre-linux-x64-tar.gz\jdk1.8.0_74\jre\lib\amd64\server\libjsig.so: A required privilege is not held by the client.
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
        at java.nio.file.Files.createSymbolicLink(Files.java:1043)
        at org.codehaus.plexus.components.io.attributes.SymlinkUtils.createSymbolicLink(SymlinkUtils.java:50)
        at org.codehaus.plexus.archiver.AbstractUnArchiver.extractFile(AbstractUnArchiver.java:327)
        at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute(TarUnArchiver.java:113)
```

**Comment by michael-o** [comment] 2017-07-04 14:07
Did you check how other tools behave on Windows in this case?

**Comment by axelfontaine** [comment] 2017-07-04 14:56
Just tested with 7-Zip: it unpacks it without complaining (no admin privileges).

**Comment by michael-o** [comment] 2017-07-04 17:44
But it doesn't create the links, right?

If it is just an `IOException` how can we handle this gracefully? How should this be logged? Add SLF4J just for this?

**Comment by plamentotev** [comment] 2017-07-04 19:50
> But it doesn't create the links, right?

It does not. It creates a regular empty file (This is for tar. I think the behavior for zip files is a bit different).

> If it is just an IOException how can we handle this gracefully?

If the symbolic link is not created then the extracted content is corrupted so I think throwing an exception is the right thing to do. If it's ok to not create a symbolic link then it should not try to create it in first place (controlled by some flag perhaps).

@axelfontaine would you please explain in bit more details what is your particular use case? Probably the handling of symbolic links on Windows could be improved but I'm not sure just ignoring the exception is the right thing to do (especially given the fact that it looks like pretty generic exception).

**Comment by axelfontaine** [comment] 2017-07-04 19:56
@plamentotev The [Flyway](https://github.com/flyway/flyway) build creates platform-specific assemblies including the Flyway jars + the JRE for that platform. Running the build on WIndows without admin rights fails with the exception above as the Linux assembly cannot be created due to the (unnecessary) symlink in the Oracle JRE Linux x64 archive.

**Comment by plamentotev** [comment] 2017-07-04 20:17
> If it's ok to not create a symbolic link then it should not try to create it in first place

Now on second second thoughts maybe I'm wrong about this. This would be valid if there a way to know that we don't have permissions to create symbolic links before trying to create one. And I'm not sure if that is possible with Java. We could check if the OS is Windows but that is not enough - admins can create symbolic links.

**Comment by plamentotev** [comment] 2017-07-04 20:17
@axelfontaine I see. I had similar project so maybe I could help you on this one. Just let me see if understood you correctly. You have platform specific assembly with the JRE so you have some thing like this

* Linux package with the Linux JRE
* Windows package with the Windows JRE

And you want to be able to create both packages on Windows, right? I had a similar project and the behavior of the Plexus Archiver was similar to what you want (due to a bug but that's another story). Instead of failing it was creating an empty regular file (as 7 zip does).  The problem is that when you pack the Linux package it will be broken. In our case it was not a problem because there is only two symbolic links in the Linux package - the one is in the Japanese documentation and we didn't hit a problem with the other one (I guess we got lucky). But that's quite fragile as you could imagine. And for some platforms it does not work. If I'm not mistaken every binary in the `bin` folder is symbolic links for the Solaris package.

I think that instead of unpacking the JRE and then packing again it would be better to just unpack the content of the JRE directly in your assembly package. Is there a reason why you can't do that?

Another issue is the permissions - if you unpack the JRE on Windows and pack it again it will mess up with the permissions.

**Comment by plamentotev** [comment] 2017-07-04 20:44
>Note that this used to work in the past. This behavior was changed maybe 2-3 years ago.

Sorry I saw that after I wrote my previous response. Maybe I'm wrong but I think you're referring to a time when Plexus Archiver didn't support symbolic links at all. The support was added about three years ago with 271ba64cf6b2e303d473dab4bb0bf3640f22e46e.

**Comment by axelfontaine** [comment] 2017-07-04 21:10
@plamentotev I see things differently. The platform the build runs on should not influence the ability to build the assembly. The issue with the Maven Assembly Plugin (which uses the Plexus Archiver) is actually that it depends on the filesystem (and its capabilities on the current platform) to build the archive, whereas it could also build it fully in-memory and be truly platform independent. This should be the default, with maybe an optional flag to revert to disk buffering for extra large payloads. Now I am not sure exactly where the best place would be to file this suggestion. This project? Somewhere else?

**Comment by plamentotev** [comment] 2017-07-04 22:08
> The issue with the Maven Assembly Plugin (which uses the Plexus Archiver) is actually that it depends on the filesystem (and its capabilities on the current platform) to build the archive, whereas it could also build it fully in-memory and be truly platform independent. This should be the default, with maybe an optional flag to revert to disk buffering for extra large payloads. Now I am not sure exactly where the best place would be to file this suggestion. This project? Somewhere else?

To some extend this is doable even with the current version of the Assembly plugin/Plexus archiver. Could you please post on the Maven mail list about what you want to achieve. I think there is a better place to discuss that.

**Comment by axelfontaine** [comment] 2017-07-04 22:32
Wouldn't the assembly plugin issue tracker be a better place?

**Comment by plamentotev** [comment] 2017-07-04 22:48
If you have feature request or bug report for the assembly plugin - yes. If you're not sure where the problem is I think the mail list is better as there are more people that could help you. Or maybe I'm wrong. @michael-o what do you think?

**Comment by axelfontaine** [comment] 2017-07-06 14:48
Filed issue with Maven Assembly Plugin: https://issues.apache.org/jira/browse/MASSEMBLY-862

**Comment by plamentotev** [comment] 2017-10-15 18:15
@axelfontaine do you have any additional concerns not solved by the issues you reported for the  Assembly Plugin or we can close this issue?

p.s. I haven't forget the issues you reported. I'm working on the modular JAR support and after I finish I'll get back to them.

**Comment by plamentotev** [comment] 2017-12-04 21:11
Since there is no feedback I'm going to close this issue. Feel free to re-open it or open another if have another issues with the symbolic  links on Windows.

**Closed by plamentotev** 2017-12-04 21:11 UTC
