### ISSUE TITLE
AbstractZipArchiver no longer respects recompressAddedZips

### ISSUE THREAD

**Issue by philwebb** [codehaus-plexus/plexus-archiver#53] opened 2016-11-29 04:55 UTC
When setting `AbstractZipArchiver.recompressAddedZips` to `false` already compressed entries should be added using the `ZipEntry.STORED` method. Unfortunately this doesn't appear to be the case.

The following can be added to `ZipArchiverTest` to demonstrate the issue.

```java
    public void testDontRecompressAddedZips() throws Exception {
         final File srcDir = new File( "src/test/resources" );
         final File zipFile = new File( "target/output/dont-recompress-added-zips.zip" );
         ZipArchiver zipArchiver = getZipArchiver( zipFile );
         zipArchiver.setRecompressAddedZips(false);
         String[] includes = { "test.zip" };
         zipArchiver.addDirectory( srcDir, includes, FileUtils.getDefaultExcludes() );
         zipArchiver.setEncoding( "UTF-8" );
         FileUtils.removePath( zipFile.getPath() );
         zipArchiver.createArchive();
         final ZipFile zf = new ZipFile( zipFile );
         assertEquals( ZipEntry.STORED, zf.getEntry("test.zip").getMethod() );
         zf.close();
	}
```

The root cause appears to be due to changes introduced in 1ddd40ba20cb5f56c0b6617a9341050051285de7 which push the header detection logic down to `wrappedRecompressor`. 

Unfortunately this doesn't work because `ConcurrentJarCreator.addArchiveEntry` stores the `mode` at the time that then entry was added and ignores any subsequent updates. You can see this by adding a breakpoint in the constructor of `ZipArchiveEntryRequest` and another in `ZipArchiveEntryRequest.getMethod()`.

**Comment by philwebb** [comment] 2016-11-29 05:06
Incidentally this bug manifests itself in `maven-assembly-plugin` v3.0 and is unfortunately quite critical with the creation of Spring Boot fat jars which rely on uncompressed entries.

**Comment by plamentotev** [comment] 2016-11-29 06:36
Hi,

Thank you for the detailed explanation. While this issue should be
solved(I'll try to fix it ASAP), if you want the fat jar to contain only
uncompresses entried maybe you could just set the whole jar compression
level to STORE or you want to compress the non-jar entries?

**Comment by philwebb** [comment] 2016-11-29 07:20
@plamentotev Unfortunately I don't think the `maven-assembly-plugin` surfaces that as an option. 

This specific requirement allows us to generate Spring Boot fat jars which are a usually a mix of `.class` files and nested `.jar` files. Only the nested jars need to be stored uncompressed and ideally we'd like to keep compression for everything else.

**Comment by plamentotev** [comment] 2016-11-29 19:28
@philwebb It provides such option in a bit obscure way. You could set arbitrary option of the archiver using `archiverConfig` (the assembly plugin will set it through reflection). For example the following configuration of the `maven-assembly-plugin` should do the trick:

```
<configuration>
    <descriptors>
        <descriptor>assembly.xml</descriptor>
    </descriptors>
    <recompressZippedFiles>false</recompressZippedFiles>
    <archiverConfig>
        <compress>false</compress>
    </archiverConfig>
</configuration>
```

It's a bit of a dirty hack as you want any non-zip files to be compresses but I hope it could help you until a proper fix is released.

**Comment by philwebb** [comment] 2016-11-29 19:32
@plamentotev Excellent, thanks for the info!

**Comment by plamentotev** [comment] 2016-11-30 19:13
Looks like that some changes in Apache Commons Compress are required in order to solve this issue. I've created an issue for those enchantments - https://issues.apache.org/jira/browse/COMPRESS-375

**Comment by snicoll** [comment] 2016-12-19 13:09
@plamentotev the commons-compress issue has been solved, awesome! Do you have a timeline for a fix here? I am asking because it will have to be incorporated in the next `maven-assembly-plugin`.

**Comment by plamentotev** [comment] 2016-12-23 19:25
@snicoll the fix is almost ready. It just needs a bit of polishing such as more test cases, javadocs, etc. Unfortunately I can't tell you when it could be merged into master as this depends on when the Apache Commons Compress 1.13 will be released.

My role in the Plexus Archiver project is not exactly known even to me :smile:. Without going into too much details - I also don't know when a version of Plexus Archiver with the fix could be released. But I did ask about this issue on the Maven Developers list so once I receive an answer I'll let you know.

p.s. If you want you could take a look at the fix - I'm working on it on [this branch](https://github.com/plamentotev/plexus-archiver/tree/fix-recompressAddedZips). It is working but still work in progress.

**Comment by michael-o** [comment] 2016-12-23 21:20
Hi guys, as soon as anyone of you has a decent PR without any regressions, I can merge it.

**Comment by michael-o** [comment] 2017-05-25 21:20
Commons Compress has been upgraded to 1.14, please revalidate this issue.

**Comment by plamentotev** [comment] 2017-05-26 05:00
It is still needed because the root cause is in Plexus Archiver. We needed newer version of Commons Compress to properly fix it. #55 fixes this issue. It's now re-based and ready to be merged.

**Closed** 2017-05-26 10:56 UTC

**Comment by snicoll** [comment] 2017-05-29 13:37
@philwebb I don't think you've created an issue to make sure the assembly plugin upgrades to plexus archiver 3.5 so I've created [MASSEMBLY-854](https://issues.apache.org/jira/browse/MASSEMBLY-854)

**Comment by snicoll** [comment] 2017-06-15 16:12
@michael-o @plamentotev the roadmap is complete for 3.5 and this blocks the release of Maven Assembly plugin 3.0.1. Is there a way to get going with this? Thanks!

**Comment by michael-o** [comment] 2017-06-15 17:21
I hoped that Commons Compress 1.15 will be released to be incorporated here. Will not happen I guess this months. I guess I will release without it.

**Comment by snicoll** [comment] 2017-06-23 09:11
@michael-o for the record I've tested the whole chain locally (including the current state of maven assembly plugin using the current state of plexus archived) and it fixes the original issue reported here. Thanks!
